apiVersion: v1
kind: Service
metadata:
  name: smtp-service
spec:
  type: NodePort
  selector:
    app: smtp-server
  ports:
    - port: 25
      targetPort: 25
      nodePort: 30083
    - port: 18080
      targetPort: 18080
      nodePort: 30084
