apiVersion: v1
kind: Service
metadata:
  name: postfix
spec:
  type: NodePort
  selector:
    app: postfix-server
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      nodePort: 30086
    - name: imap
      port: 143
      targetPort: 143
      nodePort: 30143
