apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list-deploy
  namespace: shopping-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-list-api
  template:
    metadata:
      labels:
        app: shopping-list-api
    spec:
      imagePullSecrets: 
      - name: shopping-list-regcred 
      containers:
      - name: shopping-list-api
        image: repo.matzen.io/shopping-list-app:1.0.0
        imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8080
